### ISSUE TITLE
outdated information

### ISSUE THREAD

**Issue by statistka** [MicrosoftDocs/powerbi-docs#2604]
Please, update the information for this page. It's outdated, many constructions don't work 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bcc9bde-f1c5-c7a2-c3d6-28f9ee64acb1
* Version Independent ID: d2138b8d-3283-356f-66fd-ec4ef997a798
* Content: [Tips and tricks for asking questions with Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-q-and-a-tips#qa-helps-you-phrase-the-question)
* Content Source: [powerbi-docs/consumer/end-user-q-and-a-tips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-q-and-a-tips.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @statistka .We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @statistka .  Thank you for your feedback.  Can you point out a few of the constructions that no longer work?

**Comment by statistka** [comment]
Hello Michele,

there are plenty of examples that our team discovered while working with
Q&A.

Just a couple of examples:
1) there appeared a new state "Suggested" in the linguistic schema which is
not described in the documentation
2) the same problem with "Visibility"
3) "where" started considering only as a location requirement whereas it
used to show different behavior previously. And it's not clear how to add
conditions in questions without using this word
4) "this year / month / week" works intermittently
5) "and" doesn't work properly when using it like "measure1 and measure2
and measure3 ... by dim1 and dim2"

Let me know if you need the exact tickets which we opened with Microsoft
about Q&A issues.

Kind regards, Kseniia.

**Comment by mihart** [comment]
Hi @statistka,
I've contacted the PM for this feature and asked for his help updating this page.

**Comment by mihart** [comment]
Hi @statistka ,
Just an update that the team is working on your Git issue. Besides updates to the docs, you've helped identify at least one bug, so thank you.

**Comment by statistka** [comment]
Thank you for your work.

Let me know if you need any help from me.

**Comment by mihart** [comment]
Hi again @statistka,
The team is curious to know where you read about the terms "visibility" and "suggested"?  I am assigning this bug to the Q&A team and they'll update the doc for 1 and 2.  The updates may end up in this doc (https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-tooling-advanced ) instead of the one you reference.  

Your items 3-5 appear to be bugs.  Please confirm that you've already submitted them as product bugs. 

Sorry for the back and forth, but I know we have the right people working on this now.  
Thanks.

**Comment by statistka** [comment]
Hi Michele.

I myself figured out these terms because I regularly came across them when
working with a linguistic scheme. Empirically, I figured out their
behavior, how they work.

Regarding 3-5 - I observed the wrong behavior a couple of months ago. It
seems to me that since that time something has been fixed.
I can try to find examples of those issues if it's critical.

I'm glad to help you. Don't hesitate to contact me if you have any
questions.

**Comment by mihart** [comment]
Hi @statistka ,
I see that this Git issue is a bit old, so I'm going to close it.  We got most of these issues addressed long ago and I kept it open because of "Suggested" and "Visibility".  I'm still not exactly sure how to add these  two to the article, but I've passed it along to the PMs who are working on it now. 
All the best,
the DOCS team
