### ISSUE TITLE
CSP Customers with Azure Plan

### ISSUE THREAD

**Issue by olhel** [MicrosoftDocs/powerbi-docs#3380]
We are getting requests from our customers with Azure Plan (CSP) on how to connect to the Emissions Dashboard.
Reading the documentation, it looks like it is possible also for CSP customers to use this tool.
We have tested this scenario, but are unable to connect. As end customers do not have their own Billng AccountID in this scenario, we have tried using the Billing AccountID we as a Partner has. It fails.

Is this meant to work? Or will this only work from the Partner side?
This needs clarification in the docs. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard#finding-your-companys-billing-account-id-mcampa-csp-with-azure-plan-customers-only)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by rosode** [comment]
Correct it only works for direct csp customers and partners. I’ll update the documentation.

Robin Smith
she/her
PRINCIPAL PROGRAM MANAGER
Sustainable Supply Chain
Mobile: +12064091313
***@***.******@***.***>

[Microsoft Logo]

From: olhel ***@***.***>
Sent: Monday, November 1, 2021 3:45 AM
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: Robin Smith ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/powerbi-docs] CSP Customers with Azure Plan (Issue #3380)


We are getting requests from our customers with Azure Plan (CSP) on how to connect to the Emissions Dashboard.
Reading the documentation, it looks like it is possible also for CSP customers to use this tool.
We have tested this scenario, but are unable to connect. As end customers do not have their own Billng AccountID in this scenario, we have tried using the Billing AccountID we as a Partner has. It fails.

Is this meant to work? Or will this only work from the Partner side?
This needs clarification in the docs. Thank you.

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
  *   Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
  *   Content: Connect to the Emissions Impact Dashboard - Power BI<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpower-bi%2Fconnect-data%2Fservice-connect-to-emissions-impact-dashboard%23finding-your-companys-billing-account-id-mcampa-csp-with-azure-plan-customers-only&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892295147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oEy73cH%2FqLy%2Fb3FUWUE2mhO2CALQnpODCSvL%2BR2dHWk%3D&reserved=0>
  *   Content Source: powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerbi-docs%2Fblob%2Fmaster%2Fpowerbi-docs%2Fconnect-data%2Fservice-connect-to-emissions-impact-dashboard.md&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892305141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZWxhR3IsEFJ0Pe272uSYSc0K9gSC2LP%2Bm5Lrj0Rw1BQ%3D&reserved=0>
  *   Service: powerbi
  *   Sub-service: powerbi-template-apps
  *   GitHub Login: @rosode<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frosode&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892305141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7JJ5YYDMbRapFLMr50rBSNaCQ4I%2BKLz%2FNncjFwsL5c0%3D&reserved=0>
  *   Microsoft Alias: rosode

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerbi-docs%2Fissues%2F3380&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892315134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CwHiPbZjKR23ZSy7wZIpLITt8dh6Hpa7iLQVNxZgSe0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASAO2Z55A2B7MWEBS3CWX6DUJZVR3ANCNFSM5HDXP2QQ&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892325127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FoL6R8lj5mgWxdhx1UMUP4AuiwNIxc0FLyFscJjeRtA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892325127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TdToMUUddz0eKGpkEBF0xsaE2OHvTLPthbMQU147oPg%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892335123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ovLfdosrlHqeoQOrlUm5cUMvQtXeXLNKMVc%2F9Jcd4%2FA%3D&reserved=0>.

**Comment by olhel** [comment]
> Correct it only works for direct csp customers and partners. I’ll update the documentation. Robin Smith she/her PRINCIPAL PROGRAM MANAGER Sustainable Supply Chain Mobile: +12064091313 ***@***.******@***.***> [Microsoft Logo] From: olhel ***@***.***> Sent: Monday, November 1, 2021 3:45 AM To: MicrosoftDocs/powerbi-docs ***@***.***> Cc: Robin Smith ***@***.***>; Mention ***@***.***> Subject: [MicrosoftDocs/powerbi-docs] CSP Customers with Azure Plan (Issue #3380) We are getting requests from our customers with Azure Plan (CSP) on how to connect to the Emissions Dashboard. Reading the documentation, it looks like it is possible also for CSP customers to use this tool. We have tested this scenario, but are unable to connect. As end customers do not have their own Billng AccountID in this scenario, we have tried using the Billing AccountID we as a Partner has. It fails. Is this meant to work? Or will this only work from the Partner side? This needs clarification in the docs. Thank you.
> […](#)
> ________________________________ Document Details ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking. * ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1 * Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03 * Content: Connect to the Emissions Impact Dashboard - Power BI<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpower-bi%2Fconnect-data%2Fservice-connect-to-emissions-impact-dashboard%23finding-your-companys-billing-account-id-mcampa-csp-with-azure-plan-customers-only&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892295147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oEy73cH%2FqLy%2Fb3FUWUE2mhO2CALQnpODCSvL%2BR2dHWk%3D&reserved=0> * Content Source: powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerbi-docs%2Fblob%2Fmaster%2Fpowerbi-docs%2Fconnect-data%2Fservice-connect-to-emissions-impact-dashboard.md&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892305141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZWxhR3IsEFJ0Pe272uSYSc0K9gSC2LP%2Bm5Lrj0Rw1BQ%3D&reserved=0> * Service: powerbi * Sub-service: powerbi-template-apps * GitHub Login: @rosode<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frosode&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892305141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7JJ5YYDMbRapFLMr50rBSNaCQ4I%2BKLz%2FNncjFwsL5c0%3D&reserved=0> * Microsoft Alias: rosode — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerbi-docs%2Fissues%2F3380&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892315134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CwHiPbZjKR23ZSy7wZIpLITt8dh6Hpa7iLQVNxZgSe0%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASAO2Z55A2B7MWEBS3CWX6DUJZVR3ANCNFSM5HDXP2QQ&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892325127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FoL6R8lj5mgWxdhx1UMUP4AuiwNIxc0FLyFscJjeRtA%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892325127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TdToMUUddz0eKGpkEBF0xsaE2OHvTLPthbMQU147oPg%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crosode%40microsoft.com%7C1fe17be1fb164edb973f08d99d249eae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637713602892335123%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ovLfdosrlHqeoQOrlUm5cUMvQtXeXLNKMVc%2F9Jcd4%2FA%3D&reserved=0>.

We are a direct CSP (Partner). Just to be clear: Can our customers in any way use this by themselves? Or will it only work for us (as a partner)?

**Comment by RyanBHernandez** [comment]
Hi Robin / @rosode,

I'm encountering the same issue with one of my Azure customers.  Their CSP partner is not able to provide the Account ID to be used, as per update they received, doing so will reflect details for all their other Azure customers.

In this case, as my customer's partner is a direct CSP partner, what option does my customer have to generate the Emission Impact report? 

Thanks and best regards,
Ryan

**Comment by johanvjr** [comment]
Hi @maggiesMSFT and @paulinbar, we are facing the same issue. Any news? We would like to be able to give our customers the possibility to view their own data in the Emissions Impact dashboard. 

We are a CSP direct partner.

**Comment by paulinbar** [comment]
Hi @johanvjr, I will sync with Robin, and get back to you by Friday.

**Comment by johanvjr** [comment]
Thx @paulinbar, FYI: we only have customers with the new Azure plan.

**Comment by olhel** [comment]
I asked the same question over at one of the Partner Yammer groups. And was pointed to this discussion. https://www.microsoftpartnercommunity.com/t5/CSP-Direct-Bill-Partners-Group/Connecting-Azure-Plan-customers-to-the-Emissions-Impact/m-p/52248

Appareantly this will not work for an end customer with an Azure Plan from a CSP. It will only work for the billing account that belongs o the CSP.

**Comment by rosode** [comment]
No options at this time all. We are working on ability for this to show in the Azure blade. This isn't available yet and we don't have an ETA.

Thanks!

Robin Smith
she/her
PRINCIPAL PROGRAM MANAGER
Sustainable Supply Chain
Mobile: +12064091313
***@***.******@***.***>

[Microsoft Logo]

**Comment by gjongeneel** [comment]
Hi @rosode, very curious to learn what the possibilities will be for CSP partner with Azure Plan customers to give their customers access to what is now called the 'Emissions Impact Dashboard'. At this moment, this functionality is clearly lacking and we've got a growing number of customers requesting these insights. As we have just migrated a lot of them from EA to CSP, it is a bad message that we are at this moment not able to provide this functionality (where it would be available within EA). Where could we find any updates on this subject?

**Comment by pthoor** [comment]
@rosode I also have customers wanting this, do we have any ETA for this?

**Comment by Nickbursey** [comment]
Following this as all of our customers are either charities, or ESG investment organisations...carbon emissions reporting is mandatory and on one hand we're pushing them to join forces with us - an MSP - for their billing and management of MS services...whilst on the other hand penalising them by not allowing them access to this vital data. 

Sort it out Microsoft!

**Comment by Jeharadk** [comment]
Any news on this? This is still very much relevant! 
Is there a possibility to share the pbix with us, so we can look at doing our own implementation?

**Comment by paulinbar** [comment]
Hi @Jeharadk, I'll ping the product team.

**Comment by Andy-Orme-Cloud** [comment]
We are losing customers due to this not being in place. Can we get an update ASAP?

**Comment by premsonbaby** [comment]
hi, is there any update on this?

**Comment by juleszee** [comment]
Hi Microsoft, we have also been asked by a customer for access to the Emissions Dashboard feature, we moved them over to a CSP from EA. I'm sure they won't be the last. 
Please make this a priority as we will need to declare the lack of this feature to avoid any legal ramifications, but it will also make moving over to a CSP unviable to customers who require this feature by law. 
It would also be useful if there is regular updates in this process through an official channel rather than just this thread as there is no indication to how often this is being monitored, or whether issue has a ticket raised with the product team, and whether an SLA has been assigned  to get it done.
Many thanks

**Comment by rosode** [comment]
To be clear, direct CSP customers/partners can access EID. We are addressing the indirect scenario through an API. We will update the documentation when this is ready. @gabsklad

**Comment by olhel** [comment]
> To be clear, direct CSP customers/partners can access EID. We are addressing the indirect scenario through an API. We will update the documentation when this is ready. @gabsklad

How exactly will a CSP direct customer already be able to access the EID, without access to the direct Partner's billing account?

**Comment by gabsklad** [comment]
the API will enable the direct CSP to configure Azure emissions data with their apps/dashboards as they see fit. Access to API will still need to be enabled by the direct CSP.

**Comment by miksata** [comment]
Hi @gabsklad, when will this API be available for CSP customers?

**Comment by gabsklad** [comment]
Hello, we just released the API. CSP Partners (direct billing relationship with Microsoft) can use the API to configure access for their customers. CSP customers must work with their Partner to access data.

**Comment by prakashnimmala** [comment]
> Hello, we just released the API. CSP Partners (direct billing relationship with Microsoft) can use the API to configure access for their customers. CSP customers must work with their Partner to access data.

Do we have link to the API?

**Comment by gabsklad** [comment]
updated!

[aka.ms/sustainabilityAPI](https://aka.ms/sustainabilityAPI)

**Comment by Nickbursey** [comment]
So we’re still not able to use this for customers if we’re CSP indirect?


Nick Bursey
Chief Operating Officer (co-CEO)
***@***.***

3 Church Close, Merton, Bicester, Oxfordshire, OX25 2NB

Direct:              +44 (0)203 912 9747
Service desk: +44 (0)203 912 9746
Enquiries:       +44 (0)203 912 9745

***@***.***<https://www.ethicalit.net/>

Got a minute to leave us a review? Click here<https://g.page/r/CTa8xVm0V1_yEAg/review>

**Comment by prakashnimmala** [comment]
> updated!
> 
> [aka.ms/sustainabilityAPI](https://aka.ms/sustainabilityAPI)

Thank you,  CSP partners should fill the form?

Another question is:
What should be tenant id for CSP direct partners? Customer tenant ID or Partner Azure AD tenant ID?

Please do needful ,thank you in advance

**Comment by DanDataFig** [comment]
Would be great to have some very explicit details on Partner responsibility to deliver this and how they might do it.

**Comment by paulinbar** [comment]
Hi Gabrielle, added you as an assignee. Feel free to close when you feel you've dealt with the issue.
@gabsklad

**Comment by Agazoth** [comment]
Yes. Please provide details on how csp direct suppliers are supported to deliver sustainability data to their customers. A Partner API would be nice.

**Comment by gabsklad** [comment]
Direct CSP Partners with direct billing relationship with Microsoft can use the API: go to aka.ms/sustainabilityAPI and make sure to fill out the onboarding form!

**Comment by gabsklad** [comment]
@DanDataFig 
•	[Consuming the API Overview & Video](https://techcommunity.microsoft.com/t5/fasttrack-for-azure/consuming-the-new-microsoft-cloud-for-sustainability-api/ba-p/3789280) and [sample code](https://github.com/Azure-Samples/microsoft-cloud-for-sustainability-api-sample)
•	[Onboarding and capabilities Documentation](https://learn.microsoft.com/en-us/industry/sustainability/api-overview?WT.mc_id=industry_inproduct_solncenterSustainability)
•	[OData API overview & query examples Documentation](https://learn.microsoft.com/en-us/industry/sustainability/api-odata)

**Comment by AndreasDirtl** [comment]
@gabsklad 
I looked into the videos and the thing is they once again only decribe the setup for direct customers.
They say you need the bill id for the client.
How is the setup done for CSP direct partners? What info must be provided to use the tool?

**Comment by photoliner** [comment]
As of the official documentation (https://learn.microsoft.com/en-us/industry/sustainability/api-overview?WT.mc_id=industry_inproduct_solncenterSustainability#supported-accounts): Customers who purchase Azure from a Cloud Solution Provider (CSP) aren't supported and must work directly with their CSP to learn about their cloud emissions.

Is there any plan to change this? As of today we only have one customer who's interested in this kind of report but I fear the counts will rise. Most of our customers are in a CSP relationship with us. What shall I tell them?

**Comment by mberdugo** [comment]
@photoliner, this is no longer a documentation issue.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).
